### ISSUE TITLE
Laravel 5.5 support?

### ISSUE THREAD

**Issue by drakakisgeo** [HydrefLab/iron-queue#7]
Quite straight forward. Hope it just needs a change to composer this time, but I don't have time at the moment to check it out.

**Comment by golonix** [comment]
I haven't got familiar with L5.5 yet, but will do it in next few days, so you can expect L5.5 support 😄

**Comment by drakakisgeo** [comment]
Any estimation?

**Comment by golonix** [comment]
Will try to bump it up this week.

**Comment by golonix** [comment]
Packaged bumped to L5.5. Enjoy!
